thisFile = mfilename('fullpath');
testDir = fileparts(thisFile);
phase3Root = fileparts(testDir);

M = readtable(fullfile(phase3Root, 'outputs', 'mspc_event_metrics.csv'));
assert(ismember("risk_source", string(M.Properties.VariableNames)), ...
    'Phase 3 event metrics must use risk_source.');
assert(all(ismember(["policy_transition_count", "action_switch_count", ...
        "direct_alert_switch_count"], string(M.Properties.VariableNames))), ...
    'Phase 3 event metrics must include final policy/action switch counts.');
assert(all(ismember(["nonrisk_request_episode_count", ...
        "nonrisk_confirmation_episode_count", "nonrisk_action_episode_count"], ...
        string(M.Properties.VariableNames))), ...
    'Phase 3 event metrics must include nonrisk safety-action counts.');

riskProxy = M(string(M.scenario) == "near_threshold_noise" & string(M.risk_source) == "risk_proxy", :);
mspc = M(string(M.scenario) == "near_threshold_noise" & string(M.risk_source) == "mspc", :);
hybrid = M(string(M.scenario) == "near_threshold_noise" & string(M.risk_source) == "hybrid", :);

assert(height(riskProxy) == 1 && height(mspc) == 1 && height(hybrid) == 1, ...
    'Expected risk_proxy, mspc, and hybrid near-threshold rows.');

if mspc.false_direct_alert_episode_count > riskProxy.false_direct_alert_episode_count ...
        || hybrid.false_direct_alert_episode_count > riskProxy.false_direct_alert_episode_count
    warning('Phase3:NearThresholdCalibration', ...
        'MSPC/hybrid increases near-threshold false direct alerts; report this as a calibration limitation.');
end
