% 테스트 설명:
%   요청 및 확인 정책의 에피소드 부담 지표가 기대값과 일치하는지 검증합니다.
%
% 입력:
%   테스트 내부에서 정의한 합성 데이터, 프로젝트 함수, 또는 기존 산출물을 사용합니다.
%
% 출력:
%   조건을 만족하면 조용히 종료하고, 실패하면 assert 또는 error 예외가 발생합니다.
%
% 예외:
%   파일 경로, 내부 함수 입력 조건, 저장 과정에서 발생한 MATLAB 예외가 전파될 수 있습니다.


thisFile = mfilename('fullpath');
testDir = fileparts(thisFile);
phase2Root = fileparts(testDir);

B = readtable(fullfile(phase2Root, 'outputs', 'tables', 'baseline_vs_proposed.csv'));
requiredColumns = ["request_episode_count", "false_request_episode_count", ...
    "confirmation_episode_count", "false_confirmation_episode_count", ...
    "action_episode_count", "false_action_episode_count", ...
    "nonrisk_request_episode_count", "nonrisk_confirmation_episode_count", ...
    "nonrisk_action_episode_count", ...
    "action_episodes_per_day", "request_windows_per_day", ...
    "confirmation_windows_per_day"];
switchColumns = ["policy_transition_count", "action_switch_count", ...
    "direct_alert_switch_count"];

assert(all(ismember(requiredColumns, string(B.Properties.VariableNames))), ...
    'Request/confirmation/action burden columns are missing.');
assert(all(ismember(switchColumns, string(B.Properties.VariableNames))), ...
    'Policy/action switch columns are missing.');

lowq = B(string(B.scenario) == "low_quality_artifact" ...
    & string(B.method) == "quality_aware_controller", :);
assert(height(lowq) == 1, 'Expected one low-quality proposed metrics row.');

assert(lowq.request_episode_count >= 1 || lowq.confirmation_episode_count >= 1, ...
    'Low-quality suspicious windows must create request or confirmation episodes.');
assert(lowq.action_episode_count >= 1, ...
    'Total action episodes must be present when request/confirmation routing occurs.');
assert(lowq.action_episode_count <= lowq.request_episode_count + lowq.confirmation_episode_count ...
        + lowq.direct_alert_episode_count, ...
    'Merged action episodes should not exceed the sum of component episodes.');
assert(lowq.false_action_episode_count >= lowq.false_direct_alert_episode_count, ...
    'Action burden should include direct-alert false episodes plus routing burden.');
