thisFile = mfilename('fullpath');
testDir = fileparts(thisFile);
phase2Root = fileparts(testDir);

B = readtable(fullfile(phase2Root, 'outputs', 'tables', 'baseline_vs_proposed.csv'));
requiredColumns = ["request_episode_count", "false_request_episode_count", ...
    "confirmation_episode_count", "false_confirmation_episode_count", ...
    "action_episode_count", "false_action_episode_count", ...
    "nonrisk_request_episode_count", "nonrisk_confirmation_episode_count", ...
    "nonrisk_action_episode_count", ...
    "action_episodes_per_day", "request_windows_per_day", ...
    "confirmation_windows_per_day"];
switchColumns = ["policy_transition_count", "action_switch_count", ...
    "direct_alert_switch_count"];

assert(all(ismember(requiredColumns, string(B.Properties.VariableNames))), ...
    'Request/confirmation/action burden columns are missing.');
assert(all(ismember(switchColumns, string(B.Properties.VariableNames))), ...
    'Policy/action switch columns are missing.');

lowq = B(string(B.scenario) == "low_quality_artifact" ...
    & string(B.method) == "quality_aware_controller", :);
assert(height(lowq) == 1, 'Expected one low-quality proposed metrics row.');

assert(lowq.request_episode_count >= 1 || lowq.confirmation_episode_count >= 1, ...
    'Low-quality suspicious windows must create request or confirmation episodes.');
assert(lowq.action_episode_count >= 1, ...
    'Total action episodes must be present when request/confirmation routing occurs.');
assert(lowq.action_episode_count <= lowq.request_episode_count + lowq.confirmation_episode_count ...
        + lowq.direct_alert_episode_count, ...
    'Merged action episodes should not exceed the sum of component episodes.');
assert(lowq.false_action_episode_count >= lowq.false_direct_alert_episode_count, ...
    'Action burden should include direct-alert false episodes plus routing burden.');
