function T = compare_risk_proxy_vs_mspc(windowMetrics, mspcRisk)
%COMPARE_RISK_PROXY_VS_MSPC Build side-by-side observation candidates.

    riskProxy = windowMetrics.risk_proxy;
    hybridRisk = max(riskProxy, mspcRisk);

    T = table(windowMetrics.scenario, windowMetrics.window_id, windowMetrics.day0_6, ...
        riskProxy, mspcRisk, hybridRisk, windowMetrics.q, windowMetrics.coverage, ...
        windowMetrics.true_risk, windowMetrics.true_low_quality, ...
        'VariableNames', {'scenario', 'window_id', 'day0_6', ...
        'risk_proxy', 'mspc_risk', 'hybrid_risk', 'q', 'coverage', ...
        'true_risk', 'true_low_quality'});
end
